# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './operators/gui/views/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(350, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(AuthDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setStyleSheet("font-size: 18px; font-weight: bold;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelLogin = QtWidgets.QLabel(AuthDialog)
        self.labelLogin.setObjectName("labelLogin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelLogin)
        self.loginLineEdit = QtWidgets.QLineEdit(AuthDialog)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLineEdit)
        self.labelPassword = QtWidgets.QLabel(AuthDialog)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.passwordLineEdit = QtWidgets.QLineEdit(AuthDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.loginButton = QtWidgets.QPushButton(AuthDialog)
        self.loginButton.setObjectName("loginButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loginButton)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(AuthDialog)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Authorization"))
        self.titleLabel.setText(_translate("AuthDialog", "Вход в систему"))
        self.labelLogin.setText(_translate("AuthDialog", "Login:"))
        self.loginLineEdit.setPlaceholderText(_translate("AuthDialog", "Enter login"))
        self.labelPassword.setText(_translate("AuthDialog", "Password:"))
        self.passwordLineEdit.setPlaceholderText(_translate("AuthDialog", "Enter password"))
        self.loginButton.setText(_translate("AuthDialog", "Login"))
